[package]
name = "event-store-adapter-test-utils-rs"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
ulid-generator-rs = { workspace = true, features = ["serde", "uuid"] }
testcontainers = { workspace = true }
once_cell = { workspace = true }
tokio = { workspace = true, features = ["full"] }
