[package]
name = "example-user-account-sqlite"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
event-store-adapter-rs = { path = "../../lib", features = ["sqlite"] }
chrono = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["std", "env-filter"] }
ulid-generator-rs = { workspace = true, features = ["serde", "uuid"] }
