[package]
name = "example-user-account"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
thiserror = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
event-store-adapter-rs = { path = "../../lib", features = ["dynamodb"] }
serde = { workspace = true, features = ["derive"] }
chrono = { workspace = true, features = ["serde"] }
tokio = { workspace = true, features = ["full"] }
event-store-adapter-test-utils-rs = { path = "../../test-utils" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
